settings:
  telemetry_enabled: true
active_modules:
  PowerMeter:
    module: PowermeterGSH01
    config_implementation:
      main:
        powermeter_device_id: 1
        serial_port: /dev/ttyUSB0
        baudrate: 115200
        parity: 0
        rs485_direction_gpio: -1
        ignore_echo: false
        max_clock_diff_s: 60
        num_of_retries: 1
#        publish_device_data: true
#        publish_device_diagnostics: true
  Test:
    connections:
      powermeter:
        - implementation_id: main
          module_id: PowerMeter
    module: TestPowermeter