name: Build, Lint and Test
on:
  pull_request: {}
  workflow_dispatch:
    inputs:
      runner:
        description: Which runner to use
        type: choice
        default: 'ubuntu-22.04'
        required: true
        options:
          - 'ubuntu-22.04'
          - 'large-ubuntu-22.04-xxl'
  schedule:
    - cron: '37 13,1 * * *'

jobs:
  lint:
    name: Lint
    runs-on: ${{ inputs.runner || 'ubuntu-22.04' }}
    steps:
      - name: Checkout everest-core
        uses: actions/checkout@v3
        with:
          path: source
      - name: Run clang-format
        uses: everest/everest-ci/github-actions/run-clang-format@v1.0.0
        with:
          source-dir: source
          extensions: hpp, cpp
  compile:
    name: Configure and Compile
    runs-on: ${{ inputs.runner || 'ubuntu-22.04' }}
    steps:
      # LTODO: use github actions outputs or custom github actions
      - name: Format branch name for cache key
        run: |
          BRANCH_NAME_FOR_CACHE="${GITHUB_REF_NAME//-/_}"
          echo "branch_name_for_cache=${BRANCH_NAME_FOR_CACHE}" >> "$GITHUB_ENV"
      # LTODO: use compile-main ??
      - name: Setup cache
        uses: actions/cache@v3
        with:
          path: cache
          key: compile-${{ env.branch_name_for_cache }}-${{ github.sha }}
          restore-keys: |
            compile-${{ env.branch_name_for_cache }}-
            compile-
      - name: Checkout everest-core
        uses: actions/checkout@v3
        with:
          path: source
      - name: Setup run scripts
        run: |
          mkdir scripts
          rsync -a source/.ci/build-kit/ scripts
      - name: Pull build-kit image
        run: |
          docker pull --quiet ghcr.io/everest/build-kit-alpine:latest
          docker image tag ghcr.io/everest/build-kit-alpine:latest build-kit
      - name: Compile
        run: |
          docker run \
          --volume "$(pwd):/ext" \
          --name compile-container \
          build-kit run-script compile
      - name: Upload build directory
        uses: actions/upload-artifact@v3
        with:
          name: build-directory
          path: ${{ github.workspace }}/build
      - name: Upload dist directory
        uses: actions/upload-artifact@v3
        with:
          name: dist-directory
          path: ${{ github.workspace }}/dist
  run-unit-tests:
    needs:
      - compile
    name: Run Unit Tests
    runs-on: ${{ inputs.runner || 'ubuntu-22.04' }}
    steps:
      - name: Download build directory
        uses: actions/download-artifact@v3
        with:
          name: build-directory
          path: ${{ github.workspace }}/build
      - name: Download dist directory
        uses: actions/download-artifact@v3
        with:
          name: dist-directory
          path: ${{ github.workspace }}/dist
      - name: Checkout everest-core
        uses: actions/checkout@v3
        with:
          path: source
      - name: Setup run scripts
        run: |
          mkdir scripts
          rsync -a source/.ci/build-kit/ scripts
      - name: Pull build-kit image
        run: |
          docker pull --quiet ghcr.io/everest/build-kit-alpine:latest
          docker image tag ghcr.io/everest/build-kit-alpine:latest build-kit
      - name: Run unit tests
        run: |
          docker run \
          --volume "$(pwd):/ext" \
          --name unit-tests-container \
          build-kit run-script run_unit_tests
  run-integration-tests:
    needs:
      - compile
    name: Run Integration Tests
    runs-on: ${{ inputs.runner || 'ubuntu-22.04' }}
    steps:
      - name: Download dist directory
        uses: actions/download-artifact@v3
        with:
          name: dist-directory
          path: ${{ github.workspace }}/dist
      - name: Checkout everest-core
        uses: actions/checkout@v3
        with:
          path: source
      - name: Setup run scripts
        run: |
          mkdir scripts
          rsync -a source/.ci/build-kit/ scripts
      - name: Pull build-kit image
        run: |
          docker pull --quiet ghcr.io/everest/build-kit-alpine:latest
          docker image tag ghcr.io/everest/build-kit-alpine:latest build-kit
      - name: Create integration-image
        run: |
          docker run \
          --volume "$(pwd):/ext" \
          --name test-container \
          build-kit run-script prepare_integration_tests
          docker commit test-container integration-image
      - name: Run integration tests
        run: |
          pushd source/.ci/e2e
          docker-compose run e2e-test-server run-script run_integration_tests
